Set Height 1000
Source '/vhs/.scripts/gifs/base.tape'

Output demo.gif
Require nvim

Type "pkb help"
Enter 2
Sleep 2s

Type "pkb new"
Enter
Sleep 0.8s
Down 1
Sleep 0.4s
Up 1
Sleep 0.4s
Enter
Down 3
Sleep 0.7s
Type "i"
Sleep 0.3s
Type "look how great pkb is"
Sleep 1s
Escape
Type ":wq"
Enter
Sleep 1s


Type "pkb copy"
Enter 1
Sleep 0.8s
Type "/"
Sleep 0.4s
Type "daily"
Sleep 0.4s
Down 1
Sleep 0.3s
Enter 1
Sleep 3s
